### PR TITLE
Add support for SourceLink for msquic

### PR DESCRIPTION
**Pull request by ThadHouse**
SourceLink is a technology that adds a mapping of source files to their permalinks on GitHub. This allows the VS Debugger to download sources directly from GitHub, rather then needing to find them locally. It does this automatically from information added into the PDB

Cmake files taken from https://github.com/microsoft/Azure-Kinect-Sensor-SDK/commit/aebb27acd8aa4a3aa6005689da3c8a7fe1413878

Currently, this is only supported by full Visual Studio, but there are issues in the vscode cpptools repo to add support to VS Code, along with I would assume support in windbg is in the pipeline.

### CODE REVIEW

**Comment by nibanks** [comment]
This seems to require cmake? Is there a way to do this for our kernel mode VS projects?

**Comment by ThadHouse** [comment]
We'd need to generate the SourceLink file using some other tool (Could probably do it in PS). And then hopefully /SOURCELINK works in kernel mode.

**Comment by ThadHouse** [comment]
Sadly, this might not be usable with PGO. Might need to report a bug to the linker team.

**Comment by ThadHouse** [comment]
We'll see if my trial fix works, otherwise we'll have to wait. I created the following issue for the compiler.

https://developercommunity.visualstudio.com/content/problem/1111456/sourcelink-incompatible-with-useprofile.html

**Comment by ThadHouse** [comment]
Nope. This will not work with PGO.

**Comment by ThadHouse** [comment]
I've unblocked this by making it only apply to debug builds.

**Comment by nibanks** [comment]
With the latest changes, does kernel mode build locally without first running that PowerShell script?

**Comment by ThadHouse** [comment]
I'll check. Gotta install the WDK.

**Pull request merged**
