### PR TITLE
Fix .deb Package Creation

### PR DESCRIPTION
**Pull request by nibanks**
## Description

.deb package creation had been (silently) failing with the following error:
```
Invalid package configuration: Found invalid Provides field values (\"libmsquic.so.2.0.2\"). This is not valid in a Debian package.
```
After playing around with the `fpm` tool a while it seems that we shouldn't be passing the `--provides` option for deb? Looking back at the history of this file, it used to be that way.

## Testing

I ran tested this locally and validated the contents of the .deb:

```
> dpkg-deb -c /workspaces/msquic/artifacts/dist/libmsquic_2.1.0_amd64.deb
drwxr-xrw- 0/0               0 2022-04-08 17:50 ./
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/lib/
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/lib/x86_64-linux-gnu/
-rwxrwxrwx 0/0         9683736 2022-04-08 17:46 ./usr/lib/x86_64-linux-gnu/libmsquic.lttng.so.2.1.0
lrwxrwxrwx 0/0               0 2022-04-08 17:50 ./usr/lib/x86_64-linux-gnu/libmsquic.so.2 -> libmsquic.so.2.1.0
-rwxrwxrwx 0/0         8988880 2022-04-08 17:46 ./usr/lib/x86_64-linux-gnu/libmsquic.so.2.1.0
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/share/
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/share/doc/
drwxr-xr-x 0/0               0 2022-04-08 17:50 ./usr/share/doc/libmsquic/
-rw-r--r-- 0/0             145 2022-04-08 17:50 ./usr/share/doc/libmsquic/changelog.gz
```

## Documentation

N/A

### CODE REVIEW

**Review by anrossi — APPROVED** [review]

**Comment by nibanks** [comment]
I'd really, really like some automated validation of these packages. Perhaps a simple tool that loads and calls MsQuicOpenVersion.

**Comment by wfurt** [comment]
We may be able to load the packages inside .NET tests as we generally have bigger OS coverage. Alternatively, it would probably not be too difficult to spin container and run simple QUIC app.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by nibanks** [comment]
I'm going to go ahead and merge this, but we need to get some level of validation (ideally automated) before we merge to release/2.0 branch.

**Pull request merged**
