### PR TITLE
Refactoring Azure pipeline for publishing package

### PR DESCRIPTION
**Pull request by ami-GS**
## Description

make 1 big variable then iterate all the elements.

## Testing

Using internal pipelie

## Documentation

N/A

### CODE REVIEW

**Comment by ami-GS** [comment]
hmm, 102 is just a `jobs:`

image

**Review by nibanks — DISMISSED** [review]
Love it!

**Comment by ami-GS** [comment]
This is not working yet....

**Comment by ami-GS** [comment]
Running...
https://mscodehub.visualstudio.com/msquic/_build/results?buildId=519510&view=results

**Review by nibanks — APPROVED** [review]

**Comment by ami-GS** [comment]
> Running... https://mscodehub.visualstudio.com/msquic/_build/results?buildId=519510&view=results

"fake" publish works
image

**Pull request merged**
