### PR TITLE
Add a Threat Model doc

### PR DESCRIPTION
**Pull request by nibanks**
## Description

Documentation of the threat model for MsQuic.

## Testing

N/A

## Documentation

This is new documentation.

### CODE REVIEW

**Review by ProjectsByJackHe — APPROVED** [review]
looks good.

**Comment by qzhuyan** [comment]
maybe the dynamic linked libraries should also be mentioned in this doc?

**Comment by qzhuyan** [comment]
> > maybe the dynamic linked libraries should also be mentioned in this doc?
> 
> Are you asking if we should specifically list out the libraries msquic.dll / libmsquic.so depends on?

Not sure if it is in this scope,
Maybe the reader need to be aware of which library the msquic links to, just like a reminder.

**Comment by nibanks** [comment]
> > > maybe the dynamic linked libraries should also be mentioned in this doc?
> > 
> > 
> > Are you asking if we should specifically list out the libraries msquic.dll / libmsquic.so depends on?
> 
> Not sure if it is in this scope, Maybe the reader need to be aware of which library the msquic links to, just like a reminder.

I'm not opposed to listing out dependencies (though probably in a follow up PR). I just wanted to confirm I understood your comment.

**Comment by nibanks** [comment]
We can follow up with a dependency list.

**Pull request merged**
