### PR TITLE
Add Random Loss to SpinQuic

### PR DESCRIPTION
**Pull request by nibanks**
Now that we support injecting hooks into the data path, let's make use of it in spinquic to add some random loss.

Also increases runtime to 10 min.

### CODE REVIEW

**Comment by maolson-msft** [comment]
How big of a payload does spinquic transfer in each stream? We might lose some coverage due to connections going much slower with 1% loss. I think we should go ahead and switch to a loss denominator rather than a percentage, so the loss rate can be reduced to .1% or .01%. This will become significantly more important if we add net emulation to the mix.

**Comment by Maximus-** [comment]
I think actually, a better measure here would be to do random bitflips on the outgoing or incoming (pick one) datagram. This will cause natural loss and will also exercise more code paths over time.

**Comment by nibanks** [comment]
> How big of a payload does spinquic transfer in each stream? We might lose some coverage due to connections going much slower with 1% loss. I think we should go ahead and switch to a loss denominator rather than a percentage, so the loss rate can be reduced to .1% or .01%. This will become significantly more important if we add net emulation to the mix.

The data we send is at the top of the file. Only a couple of bytes. Not much. How about we start with this, and look into increasing the stream data and decreasing the drop rate?

**Comment by nibanks** [comment]
> I think also, a good measure here would be to do random bitflips on the outgoing or incoming (pick one) datagram. This will cause natural loss and will also exercise more code paths over time. Both could work well together :-)

We can add a `-bitflip` option in an additional PR. :)

**Comment by nibanks** [comment]
Good news: the new changes seemed to help catch bugs! Bad news: there seem to be some bugs that were caught. :|

**Pull request merged**
