### PR TITLE
Initial ACK Frequency Support

### PR DESCRIPTION
**Pull request by nibanks**
First part of #929. Implements https://tools.ietf.org/html/draft-iyengar-quic-delayed-ack. Supports receiving the new ACK_FREQUENCY frame but never sends it currently.

### CODE REVIEW

**Comment by nibanks** [comment]
Anyone have any idea why I'm getting this error on my PR?
```
/home/vsts/work/1/s/src/core/crypto_tls.c: In function ‘QuicCryptoTlsDecodeTransportParameters’:
/home/vsts/work/1/s/src/core/crypto_tls.c:1212:22: error: ‘ParamLength’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1212 |         QUIC_VAR_INT ParamLength;
      |                      ^~~~~~~~~~~
cc1: all warnings being treated as errors
```
@maximus- you have any idea? It's definitely a false positive AFAICT, but I don't know why it came up on this PR.

**Comment by ThadHouse** [comment]
Thats actually not a false positive, if `BufferLength < sizeof(uint8_t) + *Offset` is true, that variable will be read uninitialized by the else if.

**Comment by nibanks** [comment]
> Thats actually not a false positive, if `BufferLength < sizeof(uint8_t) + *Offset` is true, that variable will be read uninitialized by the else if.

I don't follow. What `BufferLength`? If `QuicVarIntDecode` return `FALSE` we bail.

**Comment by ThadHouse** [comment]
Yeah I misread that. Hmm.

**Comment by Maximus-** [comment]
Not sure exactly what "may be used uninitialized in this function" entails, but it is true that there is a possible path through that function where it does not get initialized (although in that same path, it also does not get used).

**Comment by ThadHouse** [comment]
The instance of QUIC_VAR_INT right above this we do initialize to 0 even though it also can never be used uninitialized, so we can probably just do the same thing here. I want to avoid suppressing that warning. And the cost of zeroing a register is basically free.

**Comment by nibanks** [comment]
> The instance of QUIC_VAR_INT right above this we do initialize to 0 even though it also can never be used uninitialized, so we can probably just do the same thing here. I want to avoid suppressing that warning. And the cost of zeroing a register is basically free.

Perhaps, but I'd really like to know why this error is happening **now**. Any ideas? What could I have changed that caused it?

**Review by ThadHouse — APPROVED** [review]

**Pull request merged**
