### PR TITLE
Create scorecards-analysis.yml

### PR DESCRIPTION
**Pull request by nibanks**
Followed instructions from https://github.com/marketplace/actions/ossf-scorecard-action to set up the scorecard action, and then remediated any issues it found.

### CODE REVIEW

**Comment by nibanks** [comment]
Latest commit seems to run clean!

**Comment by varunsh-coder** [comment]
Hi @nibanks, I noticed you used https://app.stepsecurity.io to remediate some of the Scorecards issues. Please let me know if you have feedback, will be happy to address. I also observed you added the `step-security/harden-runner`. You get a report of the outbound calls and insights in a link in the build log, e.g. https://github.com/microsoft/msquic/runs/4883979390?check_suite_focus=true#step:3:5.

**Comment by nibanks** [comment]
> Hi @nibanks, I noticed you used https://app.stepsecurity.io to remediate some of the Scorecards issues. Please let me know if you have feedback, will be happy to address. I also observed you added the `step-security/harden-runner`. You get a report of the outbound calls and insights in a link in the build log, e.g. https://github.com/microsoft/msquic/runs/4883979390?check_suite_focus=true#step:3:5.

Yeah, I noticed the insights. Pretty neat! I am a bit hesitant to enforce the `allowed-endpoints`. What if they change slightly (not maliciously) ? I don't want to introduce extra work for us to keep them up to date.

```
- uses: step-security/harden-runner@v1
  with:
    allowed-endpoints: 
      api.github.com:443
      api.nuget.org:443
      azure.archive.ubuntu.com:80
      boringssl.googlesource.com:443
      dc.services.visualstudio.com:443
      github.com:443
      launchpad.net:443
      packages.microsoft.com:443
      ppa.launchpad.net:80
      security.ubuntu.com:80
```
For instance, what if `dc.services.visualstudio.com` starts pointing to just `services.visualstudio.com`? How will this handle TCP:port vs UDP:port (with things moving to QUIC & HTTP/3)?

**Comment by varunsh-coder** [comment]
> > Hi @nibanks, I noticed you used https://app.stepsecurity.io to remediate some of the Scorecards issues. Please let me know if you have feedback, will be happy to address. I also observed you added the `step-security/harden-runner`. You get a report of the outbound calls and insights in a link in the build log, e.g. https://github.com/microsoft/msquic/runs/4883979390?check_suite_focus=true#step:3:5.
> 
> Yeah, I noticed the insights. Pretty neat! I am a bit hesitant to enforce the `allowed-endpoints`. What if they change slightly (not maliciously) ? I don't want to introduce extra work for us to keep them up to date.
> 
> ```
> - uses: step-security/harden-runner@v1
>   with:
>     allowed-endpoints: 
>       api.github.com:443
>       api.nuget.org:443
>       azure.archive.ubuntu.com:80
>       boringssl.googlesource.com:443
>       dc.services.visualstudio.com:443
>       github.com:443
>       launchpad.net:443
>       packages.microsoft.com:443
>       ppa.launchpad.net:80
>       security.ubuntu.com:80
> ```
> 
> For instance, what if `dc.services.visualstudio.com` starts pointing to just `services.visualstudio.com`? How will this handle TCP:port vs UDP:port (with things moving to QUIC & HTTP/3)?

Thanks for the feedback! 

w.r.t `allowed-endpoints`, yes, I understand, it may lead to extra work if endpoints change. You don't have to use the `block` mode. I am thinking of how to inform the developer if endpoints change, even if it was `audit` mode. That way, it might mean something is fishy, which can then be investigated. May be I can add an `annotation` if a new endpoint is observed in future runs. Thoughts?

w.r.t things moving to QUIC & HTTP/3, I have noted that and will investigate.

**Comment by nibanks** [comment]
@varunsh-coder maybe having a `failure-mode: warn-only` or something could be an option.

**Review by anrossi — APPROVED** [review]

**Pull request merged**
