### PR TITLE
Build Windows Kernel on windows-2022 Image

### PR DESCRIPTION
**Pull request by nibanks**

### CODE REVIEW

**Comment by nibanks** [comment]
Marking as `blocked` as apparently there is no WDK compatible with Visual Studio 2022, which is the only one that `windows-2022` machines have installed.

**Comment by nibanks** [comment]
Waiting on a new WDK that's compatible with WS2022.

**Comment by nibanks** [comment]
Still failing with:
```
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
```

**Comment by thhous-msft** [comment]
This is also blocked on deciding how to handle 32 bit kernel mode binaries. A WDK installed on the VS 2022 image will never support building 32 bit kernel drivers.

https://docs.microsoft.com/en-us/windows-hardware/drivers/installing-preview-versions-wdk

**Comment by nibanks** [comment]
Looks like this is still failing on the latest:
```
Project "D:\a\1\msquic\msquic.kernel.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "release|x64".
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(440,5): Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
Project "D:\a\1\msquic\msquic.kernel.sln" (1) is building "D:\a\1\msquic\src\platform\platform.kernel.vcxproj" (2) on node 1 (default targets).
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(440,5): error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\1\msquic\src\platform\platform.kernel.vcxproj]
Done Building Project "D:\a\1\msquic\src\platform\platform.kernel.vcxproj" (default targets) -- FAILED.
```

**Comment by nibanks** [comment]
Really weird. When we build on Windows-2022 images, we can't actually **run** on Windows-2022 images. The driver fails to start. It does successfully run on our "latest" images.

And it seems out tests don't grab logs if we fail to start the driver.

**Comment by nibanks** [comment]
It's claiming a service dependency failed?
```
[Microsoft-Quic][ lib] ERROR, 1068, StartService failed.
```
Which is `ERROR_SERVICE_DEPENDENCY_FAIL`.

**Comment by nibanks** [comment]
Fixing with #3699.

**Pull request closed without merging**
