### PR TITLE
Local UDP Port Sharing for Connected Sockets (Linux only)

### PR DESCRIPTION
**Pull request by nibanks**
Partial fix for #1750, at least fixes for Linux. Also starts refactoring/improving some tests.

Still needs a test at the QUIC API layer for sharing the local socket.

### CODE REVIEW

**Review by ThadHouse — APPROVED** [review]
Do we know if this is going to cause any perf issues on linux?

**Comment by nibanks** [comment]
> Do we know if this is going to cause any perf issues on linux?

Are you asking if there is a perf difference between two client connections (to two different servers) that share local port, vs ones that don't? If so, I don't know the answer. If the question is if this would effect any existing perf tested scenario, then the answer is, I don't expect any perf difference.

**Comment by ThadHouse** [comment]
Either perf or functional issues. Isn't the reason we can't do sharing on windows a functional issue? I know we now have some tests, but I want to make sure those tests are enough.

**Comment by nibanks** [comment]
There are no perf or functional issues I am aware of on Linux related to this, beyond the weird behavior we've seen when you "share the port" but don't specify an explicit local address, and the stack ends up (sometimes) giving you one that was used by someone else.

**Pull request merged**
