### PR TITLE
2.4 Cherry Picks

### PR DESCRIPTION
**Pull request by nibanks**
Cherry pick #4625 and #4574 to v2.4

### CODE REVIEW

**Review by mtfriesen — APPROVED** [review]

**Comment by talregev** [comment]
@nibanks From my end I think you should do 3 cherry picks by this order:

- https://github.com/microsoft/msquic/pull/4525
- https://github.com/microsoft/msquic/pull/4575
- https://github.com/microsoft/msquic/pull/4574

I think you should only try one of us and do 2 PRs.

**Comment by talregev** [comment]
I will try to do a PR to [release/2.4](https://github.com/microsoft/msquic/tree/release/2.4).

**Comment by talregev** [comment]
@nibanks 
I create PR with the cherry picks and fix commit:
https://github.com/microsoft/msquic/pull/4684

**Comment by talregev** [comment]
@nibanks 
I create PR with both our changes and test on my github ci, and it working:
https://github.com/microsoft/msquic/pull/4685

**Pull request closed without merging**
