### PR TITLE
RACK based Loss Detection Only

### PR DESCRIPTION
**Pull request by nibanks**
- Disables FACK based loss detection.

### CODE REVIEW

**Comment by maolson-msft** [comment]
Why also change the time threshold? I think you should just change one thing at a time.

**Comment by nibanks** [comment]
> Why also change the time threshold? I think you should just change one thing at a time.

I can split the changes out.

**Comment by maolson-msft** [comment]
> > Why also change the time threshold? I think you should just change one thing at a time.
> 
> I can split the changes out.

Thanks. We didn't discuss changing the time threshold so it's not clear what your thinking is there. I think you should test just removing the packet threshold against your WAN perf testcases.

**Review by maolson-msft — APPROVED** [review]

**Comment by nibanks** [comment]
Going to close for now. I don't have really strong confidence in this. For instance, in DC environments (very low RTT), FACK might be very useful.

**Pull request closed without merging**
