### PR TITLE
Refactor the openssl build.

### PR DESCRIPTION
**Pull request by larseggert**
* Define some more variables to avoid repetition.
* Factor out the common parts.
* Avoid building a bunch of unnecessary components.
* Don't create makedepend files (they are created in source; problematic.)

This also has the nice side effect of cutting build time roughly in half.

### CODE REVIEW

**Comment by nibanks** [comment]
@larseggert, some build errors for Raspberry Pi:
```
make depend && make _build_sw
make[4]: Entering directory '/__w/1/s/build/linux/arm_openssl/submodules/openssl'
make[4]: Leaving directory '/__w/1/s/build/linux/arm_openssl/submodules/openssl'
make[4]: Entering directory '/__w/1/s/build/linux/arm_openssl/submodules/openssl'
arm-raspbian10-linux-gnueabihf-/usr/local/bin/arm-raspbian10-linux-gnueabihf-gcc  -I. -Iinclude -Iapps/include -I../../../../../submodules/openssl -I../../../../../submodules/openssl/include -I../../../../../submodules/openssl/apps/include  -fPIC -pthread -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_PIC -DOPENSSLDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/ssl\"" -DENGINESDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/lib/engines-3\"" -DMODULESDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/lib/ossl-modules\"" -DNDEBUG -DL_ENDIAN  -c -o apps/lib/libapps-lib-app_params.o ../../../../../submodules/openssl/apps/lib/app_params.c
arm-raspbian10-linux-gnueabihf-/usr/local/bin/arm-raspbian10-linux-gnueabihf-gcc  -I. -Iinclude -Iapps/include -I../../../../../submodules/openssl -I../../../../../submodules/openssl/include -I../../../../../submodules/openssl/apps/include  -fPIC -pthread -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_PIC -DOPENSSLDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/ssl\"" -DENGINESDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/lib/engines-3\"" -DMODULESDIR="\"/__w/1/s/build/linux/arm_openssl/openssl/lib/ossl-modules\"" -DNDEBUG -DL_ENDIAN  -c -o apps/lib/libapps-lib-app_rand.o ../../../../../submodules/openssl/apps/lib/app_rand.c
/bin/sh: 1: arm-raspbian10-linux-gnueabihf-/usr/local/bin/arm-raspbian10-linux-gnueabihf-gcc: not found
make[4]: *** [apps/lib/libapps-lib-app_rand.o] Error 127
make[4]: *** Waiting for unfinished jobs....
Makefile:2013: recipe for target 'apps/lib/libapps-lib-app_rand.o' failed
/bin/sh: 1: arm-raspbian10-linux-gnueabihf-/usr/local/bin/arm-raspbian10-linux-gnueabihf-gcc: not found
Makefile:2011: recipe for target 'apps/lib/libapps-lib-app_params.o' failed
make[4]: Leaving directory '/__w/1/s/build/linux/arm_openssl/submodules/openssl'
make[4]: *** [apps/lib/libapps-lib-app_params.o] Error 127
Makefile:1162: recipe for target 'build_sw' failed
make[3]: Leaving directory '/__w/1/s/build/linux/arm_openssl/submodules/openssl'
make[3]: *** [build_sw] Error 2
make[2]: *** [openssl/include] Error 2
CMakeFiles/OpenSSL.dir/build.make:82: recipe for target 'openssl/include' failed
make[2]: Leaving directory '/__w/1/s/build/linux/arm_openssl'
CMakeFiles/Makefile2:615: recipe for target 'CMakeFiles/OpenSSL.dir/all' failed
```

**Comment by larseggert** [comment]
Can you kick that one failed run again? It seems like it timed out?

**Pull request merged**
