### PR TITLE
Execute StreamShutdown Inline on Callbacks

### LINKED ISSUE #1520: Support Immediate Stream Abort in PEER_STREAM_STARTED Event
### Describe the feature you'd like supported

There are scenarios (HTTP/3 GOAWAY) where the app needs to immediately reject an incoming stream. Currently `StreamShutdown` queues up that work instead of executing immediately, even on the callback thread. This opens up the app to additional notifications for the stream that they don't want/need.

We need a way for an app to immediately abort the incoming stream.

### Proposed solution

The simplest way is to just execute `StreamShutdown` inline when called on the callback.

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #1520.

### CODE REVIEW

**Comment by anrossi** [comment]
Did you intend to add the clog change to this PR?

**Comment by anrossi** [comment]
Also, do we have tests which exercise both paths?

**Comment by nibanks** [comment]
> Did you intend to add the clog change to this PR?

Nope. Already removed.

**Comment by nibanks** [comment]
> Also, do we have tests which exercise both paths?

I believe so. I first pushed this to just run existing tests. I will review the test coverage to make sure.

**Review by anrossi — APPROVED** [review]

**Pull request merged**
