### PR TITLE
Add QUIC_STATUS_ALPN_IN_USE to C# interop

### PR DESCRIPTION
**Pull request by rzikm**
## Description

This PR adds the `QUIC_STATUS_ALPN_IN_USE` to the generated C# interop.

## Testing

Tested with local build of .NET Runtime and on the CI as part of https://github.com/dotnet/runtime/pull/74754.

## Documentation

No.

### CODE REVIEW

**Comment by nibanks** [comment]
Looks like you accidentally changed the googletest submodule.

**Comment by rzikm** [comment]
Should be good now

**Review by nibanks — APPROVED** [review]

**Comment by nibanks** [comment]
@rzikm is this going to be needed to be backported to release/2.1?

**Comment by rzikm** [comment]
> @rzikm is this going to be needed to be backported to release/2.1?

No, there is no functional change in this PR and we copy the interop sources to .NET runtime repo. Anyway, the .NET-side change related to this would not meet the bar for getting it to the 7.0 release at this point.

**Pull request merged**
