### PR TITLE
Latest QuicTLS test

### PR DESCRIPTION
**Pull request by tmshort**
Test for https://github.com/quictls/openssl/pull/61

### CODE REVIEW

**Comment by nibanks** [comment]
@tmshort is there something in here that would make openssl slower? The tests on the latest Windows version timed out. (there was another test that failed to configure properly for some reason). I'm rerunning both.

**Comment by tmshort** [comment]
There really aren't that many changes in the branch. Went from commit  df92821e31 to 357353d359. In this PR you can see the diffs to the openssl submodule. (File changed indicates (1), but the it's showing the submodule diff)

**Comment by tmshort** [comment]
Are they timing out due to being slow, or errors?
This introduces the possibility of an error when the legacy session ID is used:
https://github.com/quictls/openssl/compare/df92821e310497f8664b30cff24da897996d3cce...357353d35954f1de571eda2e998df99bfc0d116f#diff-ad8331ef7b6455d502e8ad14077f12dfd78ee38d79be0227f2c99a8a2eafd8a5R1599

Otherwise, the changes are minimal/innocuous.

**Comment by nibanks** [comment]
> Are they timing out due to being slow, or errors?

It seemed to be just general slowness. The tests were all passing still.

**Comment by tmshort** [comment]
Odd. You can see for yourself what there really should've have been anything significant performance-wise... hmmm

**Comment by nibanks** [comment]
Well, maybe it was just a one-off. The tests all passed on rerun. I'd say your quictls changes should be fine.

**Pull request closed without merging**
