### PR TITLE
Always set execution config for 'no sleep'

### PR DESCRIPTION
**Pull request by ami-GS**
## Description

sleeping with normal socket, but no sleep with special socket (feature).

## Testing

see netperf?

## Documentation

N/A

### CODE REVIEW

**Comment by nibanks** [comment]
> sleeping with normal socket, but no sleep with special socket (feature).

Why?

**Comment by ami-GS** [comment]
I just surprised that xdp mode uses 100% CPU, but epoll is 0%. Is this expected?

**Comment by nibanks** [comment]
XDP is set up to use polling, yes. But not sockets.

**Comment by ami-GS** [comment]
How about epoll? it is named poll as well.

**Comment by nibanks** [comment]
> How about epoll? it is named poll as well.

No. Still no polling for it. Only XDP right now.

**Pull request closed without merging**
