### PR TITLE
pkg_config setting for arm

### PR DESCRIPTION
**Pull request by ami-GS**
## Description

Arm releases are affected by newer docker image which has pkg_config.
build.ps1 to cover the setting.

## Testing

See automation

### CODE REVIEW

**Review by nibanks — APPROVED** [review]
Please make sure the CI passes before merging. Thanks for doing these fixes!

**Comment by ami-GS** [comment]
When will this CI finish?

**Comment by nibanks** [comment]
> When will this CI finish?

I think something broke. Try closing and reopening the PR to see if that will kick the CI. If not, try a force push.

**Comment by ami-GS** [comment]
The error looks not related to my change?
android with openssl3 build error and msquic.dll not found.

**Pull request merged**
