### PR TITLE
Consume XDP fix for TX hangs

### PR DESCRIPTION
**Pull request by csujedihy**
## Description

Remove the workaround in QUIC for XDP TX hangs.

## Testing

Covered by existing tests.

### CODE REVIEW

**Review by nibanks — COMMENTED** [review]
Should you be pointing to a new SDK?

**Comment by csujedihy** [comment]
> Should you be pointing to a new SDK?

I updated both xdp.zip and xdp-latest.zip to the XDP v0.16.1.

**Comment by nibanks** [comment]
> > Should you be pointing to a new SDK?
> 
> I updated both xdp.zip and xdp-latest.zip to XDP v0.16.1.

Ok!

**Review by nibanks — APPROVED** [review]
Please look at the CI failure to make sure it's not caused by this.

**Comment by csujedihy** [comment]
> Please look at the CI failure to make sure it's not caused by this.

It's a spinquic watchdog timeout and I think I have hit it a few times a few weeks ago.

**Comment by nibanks** [comment]
> > Please look at the CI failure to make sure it's not caused by this.
> 
> It's a spinquic watchdog timeout and I think I have hit it a few times a few weeks ago.

Ok. Ship it!

**Pull request merged**
