### PR TITLE
Fix No Idle Timeout TP Bug

### LINKED ISSUE #363: Interop Server isn't Sending Idle Timeout TP
### Describe the bug

@rmarx pointed out on the quicdev Slack that our interop server doesn't seem to be sending out the idle timeout transport parameter. I confirmed this in a log from a different connection on the server.

### Steps to reproduce the behavior

1. Run quicinteropserver
2. Connect to the server
3. Verify that the server indicates an idle timeout

### Expected vs actual behavior

I looked through the code and the only way we shouldn't be sending an idle timeout is if it's set to zero:

```C
        if (Connection->IdleTimeoutMs != 0) {
            LocalTP.Flags |= QUIC_TP_FLAG_IDLE_TIMEOUT;
            LocalTP.IdleTimeout = Connection->IdleTimeoutMs;
        }
```

So, somehow this value must be getting set to zero. Either it was somehow zero'ed out generally, read before being set, or explicitly set to zero by something (I assume a bug). I looked at the quicinteropserver code and it doesn't ever set an idle timeout at the app layer, so it should be using the 30 second default. I also validated there is no global registry key set to change the default.

### PR DESCRIPTION
**Pull request by nibanks**
Fix #363.

This PR first adds more configurable functionality to the quicinterop tool to allow for easier/custom debugging and log collection. Second it fixes a bug in the settings where the ValueLen field was being used on output when the storage query was failing. Apparently, the Windows APIs were changing the value of that, causing the "default" logic to end up setting a value of zero to the setting.

### CODE REVIEW

**Comment by maolson-msft** [comment]
I don't understand the MultiValue thing. Does the value retrieved by QuicStorageReadValue not have a single defined size?

**Comment by nibanks** [comment]
> I don't understand the MultiValue thing. Does the value retrieved by QuicStorageReadValue not have a single defined size?

We allow for the setting to be set with either a DWord or QWord.

**Comment by maolson-msft** [comment]
> > I don't understand the MultiValue thing. Does the value retrieved by QuicStorageReadValue not have a single defined size?
> 
> We allow for the setting to be set with either a DWord or QWord.

Why?

**Comment by nibanks** [comment]
> > > I don't understand the MultiValue thing. Does the value retrieved by QuicStorageReadValue not have a single defined size?
> > 
> > 
> > We allow for the setting to be set with either a DWord or QWord.
> 
> Why?

Because I wanted to support it. It's common that the value does not need a QWord, so it's likely the the person writing the registry would set a DWord.

**Pull request merged**
