### PR TITLE
Increase Receive Buffer Drain Ratio

### PR DESCRIPTION
**Pull request by ThadHouse**
Perf testing was seeing that we were hitting stream flow control rate limiting, causing instabilities in perf results. Increasing the ratio helps solve this issue by hitting that flow control limit much less often.

Also updates the perf CI runner to allow grabbing logs for remote tests.

### CODE REVIEW

**Comment by maolson-msft** [comment]
How much instability?

**Comment by ThadHouse** [comment]
```
Run 1: 3123786 kbps
Run 2: 3130550 kbps
Run 3: 2857508 kbps
Run 4: 991619 kbps
Run 5: 3258607 kbps
Run 6: 2173664 kbps
Run 7: 2989996 kbps
Run 8: 1864926 kbps
Run 9: 1896891 kbps
Run 10: 1284220 kbps
```

That's what test results looked like before this change. Some fast runs, some slow runs, and anywhere in between.

**Comment by nibanks** [comment]
> How much instability?

A lot, @maolson-msft, a lot. After looking through the traces it was found to be caused by stream flow control.

**Comment by nibanks** [comment]
Latest results:
```
Run 1: 2919296 kbps
Run 2: 3839305 kbps
Run 3: 3022447 kbps
Run 4: 3888768 kbps
Run 5: 3034535 kbps
Run 6: 3535294 kbps
Run 7: 3055724 kbps
Run 8: 4017871 kbps
Run 9: 3029709 kbps
Run 10: 3933801 kbps
Median: 3055724 kbps (+109.7%)
Master: 1457177 kbps
```

**Pull request merged**
